---
root: true
extends:
  - '@epaew/eslint-config/react-typescript'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-empty-function': off
overrides:
  - files:
      - jest.config.js
    env:
      node: true
  - files:
      - '__mocks__/*'
      - '__tests__/*'
    plugins:
      - '@typescript-eslint'
      - react
    rules:
      '@typescript-eslint/no-explicit-any': off
      react/prop-types: off
