---
root: true
env:
  es2017: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-explicit-any': off
  prettier/prettier: error
settings:
  react:
    version: detect
